#!/usr/bin/env python3
"""Regenerate PhyloPic-sourced species silhouettes from the canonical CSV map.

``data/db_backup/species_svg_map.csv`` is the single source of truth. For every row
whose ``ui_svg_type == "phylopic"`` this downloads the recorded PhyloPic image
(by ``phylopic_uuid``) as ``assets/species_svg/<species_id>.svg``.

Rows traced from the hand-drawn jigsaw (``ui_svg_type == "jigsaw"``) are not on
PhyloPic — they reference a UUID only for attribution — and are skipped, as is
``homo_sapiens`` (``flag == "special"``). Those files cannot be regenerated by
this script; they are curated art.

Usage::

    uv run python scripts/download_phylopic.py            # write into assets/species_svg/
    uv run python scripts/download_phylopic.py --check    # diff against committed set, no writes
    uv run python scripts/download_phylopic.py --species pinctada_fucata
"""
from __future__ import annotations

import logging
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import polars as pl
import typer

REPO_ROOT = Path(__file__).resolve().parents[1]
SVG_MAP_CSV = REPO_ROOT / "data" / "db_backup" / "species_svg_map.csv"
SPECIES_SVG_DIR = REPO_ROOT / "assets" / "species_svg"
CHECK_DIR = REPO_ROOT / "data" / "interim" / "phylopic_check"

IMAGES_BASE = "https://images.phylopic.org"
USER_AGENT = "materialized-enhancements/phylopic-sync (+https://enhancement.bio)"

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("download_phylopic")

app = typer.Typer(add_completion=False)


# A PhyloPic image is either uploaded as SVG (`source.svg`) or as a raster whose
# vectorization is served at `vector.svg`. Try the original first, then the vector.
_SVG_VARIANTS = ("source.svg", "vector.svg")


def _fetch(url: str, timeout: int) -> bytes:
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=timeout) as resp:
        return resp.read()


def fetch_svg(uuid: str, timeout: int = 30) -> tuple[bytes, str]:
    """Download SVG bytes for a PhyloPic image UUID; returns (bytes, variant_used)."""
    last_error: HTTPError | None = None
    for variant in _SVG_VARIANTS:
        try:
            return _fetch(f"{IMAGES_BASE}/images/{uuid}/{variant}", timeout), variant
        except HTTPError as exc:
            if exc.code != 404:
                raise
            last_error = exc
    raise last_error if last_error else FileNotFoundError(uuid)


def phylopic_rows(df: pl.DataFrame) -> list[dict]:
    """Rows that should be (re)downloaded from PhyloPic, in CSV order."""
    return [
        row
        for row in df.iter_rows(named=True)
        if row["ui_svg_type"] == "phylopic"
        and row["flag"] != "special"
        and row["phylopic_uuid"]
    ]


@app.command()
def main(
    check: bool = typer.Option(
        False,
        "--check",
        help="Download into a scratch dir and diff against the committed SVGs; do not overwrite.",
    ),
    species: str = typer.Option(
        "", "--species", help="Only process this species_id."
    ),
) -> None:
    """Download PhyloPic-sourced silhouettes named in species_svg_map.csv."""
    df = pl.read_csv(SVG_MAP_CSV)
    total = df.height
    rows = phylopic_rows(df)
    if species:
        rows = [r for r in rows if r["species_id"] == species]

    skipped = total - len(phylopic_rows(df))
    out_dir = CHECK_DIR if check else SPECIES_SVG_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    logger.info(
        "%d species in map; %d PhyloPic-sourced (downloadable), %d skipped "
        "(jigsaw-traced / special).",
        total,
        len(phylopic_rows(df)),
        skipped,
    )
    logger.info("Mode: %s → %s\n", "CHECK (diff only)" if check else "WRITE", out_dir)

    identical: list[str] = []
    differs: list[str] = []
    written: list[str] = []
    failed: list[str] = []

    for i, row in enumerate(rows, 1):
        sid = row["species_id"]
        uuid = row["phylopic_uuid"]
        logger.info("[%d/%d] %s  (%s)", i, len(rows), sid, uuid)

        try:
            data, variant = fetch_svg(uuid)
        except (HTTPError, URLError, TimeoutError) as exc:
            logger.warning("  FAILED: %s", exc)
            failed.append(sid)
            continue

        committed = SPECIES_SVG_DIR / f"{sid}.svg"
        if check:
            if not committed.exists():
                logger.info("  [%s] downloaded %d bytes; no committed file to compare", variant, len(data))
                differs.append(sid)
            elif committed.read_bytes() == data:
                logger.info("  [%s] identical to committed (%d bytes)", variant, len(data))
                identical.append(sid)
            else:
                logger.info(
                    "  [%s] DIFFERS from committed (download %d B vs committed %d B)",
                    variant,
                    len(data),
                    committed.stat().st_size,
                )
                differs.append(sid)
            (CHECK_DIR / f"{sid}.svg").write_bytes(data)
        else:
            (out_dir / f"{sid}.svg").write_bytes(data)
            logger.info("  saved %s [%s] (%d bytes)", f"{sid}.svg", variant, len(data))
            written.append(sid)

    logger.info("\n%s", "=" * 60)
    if check:
        logger.info("identical: %d  %s", len(identical), identical)
        logger.info("differs/new: %d  %s", len(differs), differs)
    else:
        logger.info("written: %d", len(written))
    logger.info("failed: %d  %s", len(failed), failed)
    logger.info(
        "not from PhyloPic (skipped, curated): %d — see ui_svg_type=='jigsaw' "
        "and flag=='special' rows in %s",
        skipped,
        SVG_MAP_CSV.name,
    )


if __name__ == "__main__":
    app()
